---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: "v4.5.0"
      hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-executables-have-shebangs
          - id: check-yaml
          - id: check-xml
          - id: end-of-file-fixer
