#!/usr/bin/env python3
"""
MySQL to PostgreSQL Schema Converter for TrinityCore

This module provides the main entry point for converting MySQL SQL dumps
to PostgreSQL format. It uses a pipeline architecture internally:

1. Preprocessing - Remove mysqldump artifacts
2. Splitting - Split into individual statements
3. Classification - Route DDL/DML to appropriate converters
4. Transformation - Apply type and syntax conversions
5. Postprocessing - Final cleanup

The MySQLToPostgreSQLConverter class provides a backward-compatible API
while delegating to the modular pipeline implementation.
"""

import argparse
import sys
import traceback
from pathlib import Path

from trinity_postgres_tools.pipeline import (
    ConversionOptions,
    create_default_pipeline,
)


class MySQLToPostgreSQLConverter:
    """
    Converts MySQL SQL to PostgreSQL format.

    This is a facade over the pipeline architecture that maintains
    backward compatibility with the original API.

    Attributes:
        debug: Enable debug output
        stats: Conversion statistics (ddl_statements, dml_statements, etc.)
    """

    def __init__(self, debug: bool = False) -> None:
        """
        Initialize the converter.

        Args:
            debug: Enable debug logging to stderr
        """
        self.debug = debug
        self._options = ConversionOptions(debug=debug)
        self._pipeline = create_default_pipeline(self._options)
        self.stats: dict[str, int] = {
            "ddl_statements": 0,
            "dml_statements": 0,
            "other_statements": 0,
            "sqlglot_errors": 0,
        }

    def log_debug(self, message: str) -> None:
        """Log debug message if debug mode is enabled."""
        if self.debug:
            print(f"DEBUG: {message}", file=sys.stderr)

    def convert(self, content: str) -> str:
        """
        Convert MySQL SQL content to PostgreSQL.

        Args:
            content: MySQL SQL content (may contain multiple statements)

        Returns:
            PostgreSQL SQL content
        """
        result, ctx = self._pipeline.convert_with_context(content)

        # Update stats from context
        self.stats["ddl_statements"] = ctx.stats.ddl_count
        self.stats["dml_statements"] = ctx.stats.dml_count
        self.stats["other_statements"] = ctx.stats.other_count
        self.stats["sqlglot_errors"] = ctx.stats.sqlglot_errors

        return result

    def convert_file(
        self, input_file: Path, output_file: Path | None = None
    ) -> str:
        """
        Convert a MySQL SQL file to PostgreSQL.

        Args:
            input_file: Path to input MySQL SQL file
            output_file: Optional path to write output (if None, returns result)

        Returns:
            Converted PostgreSQL SQL content
        """
        self.log_debug(f"Converting file: {input_file}")

        with input_file.open(encoding="utf-8") as f:
            content = f.read()

        self.log_debug(f"Read {len(content)} bytes")

        # Reset stats
        self.stats = {
            "ddl_statements": 0,
            "dml_statements": 0,
            "other_statements": 0,
            "sqlglot_errors": 0,
        }

        result = self.convert(content)

        # Add header
        header = """\
-- PostgreSQL database schema converted from MySQL
-- Generated by TrinityCore MySQL to PostgreSQL converter
-- Pipeline architecture: preprocessing, splitting, transformation, postprocessing

"""
        result = header + result

        if output_file:
            with output_file.open("w", encoding="utf-8") as f:
                f.write(result)
            self.log_debug(f"Output written to: {output_file}")

        self.log_debug(f"Stats: {self.stats}")

        return result


def convert_mysql_to_postgres(
    sql: str,
    debug: bool = False,
) -> str:
    """
    Convenience function for one-shot conversion.

    Args:
        sql: MySQL SQL content
        debug: Enable debug output

    Returns:
        PostgreSQL SQL content
    """
    converter = MySQLToPostgreSQLConverter(debug=debug)
    return converter.convert(sql)


def convert_file(
    input_file: str | Path,
    output_file: str | Path | None = None,
    debug: bool = False,
) -> str:
    """
    Convenience function for file conversion.

    Args:
        input_file: Path to input MySQL SQL file
        output_file: Optional path to write output
        debug: Enable debug output

    Returns:
        PostgreSQL SQL content
    """
    converter = MySQLToPostgreSQLConverter(debug=debug)
    return converter.convert_file(
        Path(input_file),
        Path(output_file) if output_file else None,
    )


def convert_directory(
    input_dir: str | Path,
    output_dir: str | Path | None = None,
    debug: bool = False,
) -> dict[str, int]:
    """
    Convert all SQL files in a directory recursively.

    Creates a 'postgresql' subdirectory in input_dir if output_dir is None.
    Preserves directory structure.

    Args:
        input_dir: Path to directory containing MySQL SQL files
        output_dir: Optional output directory (defaults to input_dir/postgresql)
        debug: Enable debug output

    Returns:
        Dict with conversion statistics (total, success, failed)
    """
    input_path = Path(input_dir)
    if output_dir:
        output_path = Path(output_dir)
    else:
        output_path = input_path / "postgresql"

    output_path.mkdir(parents=True, exist_ok=True)

    converter = MySQLToPostgreSQLConverter(debug=debug)
    stats = {"total": 0, "success": 0, "failed": 0}

    # Find all SQL files recursively, excluding postgresql subdirectory
    sql_files = [
        f for f in input_path.rglob("*.sql")
        if "postgresql" not in f.parts
    ]

    for sql_file in sql_files:
        stats["total"] += 1
        # Compute relative path from input_dir
        rel_path = sql_file.relative_to(input_path)
        out_file = output_path / rel_path

        # Create parent directories
        out_file.parent.mkdir(parents=True, exist_ok=True)

        try:
            converter.convert_file(sql_file, out_file)
            stats["success"] += 1
            if debug:
                print(f"Converted: {rel_path}", file=sys.stderr)
        except Exception as e:
            stats["failed"] += 1
            print(f"Failed: {rel_path}: {e}", file=sys.stderr)

    return stats


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Convert MySQL schema to PostgreSQL for TrinityCore"
    )
    parser.add_argument(
        "input_file",
        help="Input MySQL SQL file or directory (with -d/--directory)",
    )
    parser.add_argument(
        "output_file",
        nargs="?",
        help="Output PostgreSQL SQL file or directory (optional)",
    )
    parser.add_argument("--debug", action="store_true", help="Enable debug output")
    parser.add_argument(
        "-d", "--directory",
        action="store_true",
        help="Convert all SQL files in directory recursively, creating postgresql/ subdirectory",
    )

    args = parser.parse_args()

    input_path = Path(args.input_file)
    output_path = Path(args.output_file) if args.output_file else None

    if not input_path.exists():
        print(f"Error: Input path {input_path} does not exist", file=sys.stderr)
        sys.exit(1)

    if args.directory:
        # Directory conversion mode
        if not input_path.is_dir():
            print(f"Error: {input_path} is not a directory", file=sys.stderr)
            sys.exit(1)

        try:
            stats = convert_directory(input_path, output_path, debug=args.debug)
            print(f"Conversion complete: {stats['success']}/{stats['total']} files converted", file=sys.stderr)
            if stats["failed"] > 0:
                print(f"Failed: {stats['failed']} files", file=sys.stderr)
                sys.exit(1)
        except Exception as e:
            print(f"Error converting directory: {e}", file=sys.stderr)
            if args.debug:
                traceback.print_exc()
            sys.exit(1)
    else:
        # Single file conversion mode
        converter = MySQLToPostgreSQLConverter(debug=args.debug)

        try:
            result = converter.convert_file(input_path, output_path)

            if not output_path:
                print(result)

            if args.debug:
                print(f"\nConversion stats: {converter.stats}", file=sys.stderr)

        except Exception as e:
            print(f"Error converting file: {e}", file=sys.stderr)
            if args.debug:
                traceback.print_exc()
            sys.exit(1)


if __name__ == "__main__":
    main()
