"""
Integration tests for the complete conversion pipeline.

Test cases are based on real examples extracted from TrinityCore database dumps:
- TDB_full_world_442.25051_2025_05_11.sql (Cataclysm Classic world database)
- sql/base/auth_database.sql (Authentication database schema)
"""

from trinity_postgres_tools.converter import MySQLToPostgreSQLConverter
from trinity_postgres_tools.pipeline import create_default_pipeline


class TestPipelineIntegration:
    """Test the complete conversion pipeline."""

    def test_simple_create_table(self):
        """Convert a simple CREATE TABLE statement."""
        mysql = "CREATE TABLE test (id INT PRIMARY KEY, name VARCHAR(255));"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "CREATE TABLE" in result
        assert "INTEGER" in result
        assert "VARCHAR" in result

    def test_create_with_auto_increment(self):
        """Convert AUTO_INCREMENT to SERIAL or IDENTITY."""
        mysql = "CREATE TABLE test (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (id));"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # sqlglot converts to GENERATED BY DEFAULT AS IDENTITY (modern PostgreSQL)
        # or SERIAL (traditional PostgreSQL)
        assert "SERIAL" in result or "IDENTITY" in result
        assert "AUTO_INCREMENT" not in result

    def test_insert_with_escapes(self):
        """Convert INSERT with escape sequences."""
        mysql = r"INSERT INTO test VALUES (1, 'Zul\'Farrak');"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO test VALUES" in result
        assert "''" in result  # Escaped quote as doubled quote

    def test_insert_with_hex_literal(self):
        """Convert hex literals to integers.

        0xDEADBEEF = 3735928559 (unsigned), but since this exceeds
        INT_MAX (2147483647), it's converted to signed: -559038737
        """
        mysql = "INSERT INTO test VALUES (1, 0xDEADBEEF);"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # Hex is converted to integer, then unsigned->signed conversion applies
        assert "-559038737" in result

    def test_mixed_ddl_dml(self):
        """Convert mixed DDL and DML statements."""
        mysql = """
CREATE TABLE test (id INT PRIMARY KEY);
INSERT INTO test VALUES (1);
INSERT INTO test VALUES (2);
"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "CREATE TABLE" in result
        assert "INSERT INTO test VALUES" in result

    def test_removes_engine_clause(self):
        """Remove ENGINE clause from CREATE TABLE."""
        mysql = "CREATE TABLE test (id INT) ENGINE=InnoDB;"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "ENGINE" not in result

    def test_removes_charset_clause(self):
        """Remove DEFAULT CHARSET clause."""
        mysql = "CREATE TABLE test (id INT) DEFAULT CHARSET=utf8mb4;"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "CHARSET" not in result

    def test_removes_mysqldump_artifacts(self):
        """Remove mysqldump artifacts like LOCK TABLES."""
        mysql = """
LOCK TABLES test WRITE;
INSERT INTO test VALUES (1);
UNLOCK TABLES;
"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "LOCK TABLES" not in result
        assert "UNLOCK TABLES" not in result
        assert "INSERT INTO test VALUES" in result

    def test_removes_set_names(self):
        """Remove SET NAMES statements."""
        mysql = """SET NAMES utf8;
INSERT INTO test VALUES (1);"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "SET NAMES" not in result
        assert "INSERT INTO test VALUES" in result


class TestConverterFacade:
    """Test the MySQLToPostgreSQLConverter facade."""

    def test_convert_simple(self):
        """Convert simple SQL."""
        converter = MySQLToPostgreSQLConverter()
        mysql = "CREATE TABLE test (id INT PRIMARY KEY);"
        result = converter.convert(mysql)

        assert "CREATE TABLE" in result
        assert "INTEGER" in result

    def test_tracks_stats(self):
        """Converter tracks statistics."""
        converter = MySQLToPostgreSQLConverter()
        mysql = """
CREATE TABLE test (id INT PRIMARY KEY);
INSERT INTO test VALUES (1);
INSERT INTO test VALUES (2);
"""
        converter.convert(mysql)

        assert converter.stats["ddl_statements"] == 1
        assert converter.stats["dml_statements"] == 2

    def test_debug_mode(self):
        """Debug mode doesn't raise errors."""
        converter = MySQLToPostgreSQLConverter(debug=True)
        mysql = "CREATE TABLE test (id INT);"
        result = converter.convert(mysql)

        assert "CREATE TABLE" in result


class TestEscapeSequenceHandling:
    """Test critical escape sequence edge cases."""

    def test_backslash_before_quote(self):
        r"""Handle the critical \\' edge case (backslash before quote)."""
        mysql = r"INSERT INTO test VALUES ('path\\', 'text');"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # The backslash should be preserved
        assert "\\\\" in result or "path" in result

    def test_doubled_quote_preserved(self):
        """Preserve doubled single quotes."""
        mysql = "INSERT INTO test VALUES ('it''s a test');"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "''" in result

    def test_escaped_quote_converted(self):
        r"""Convert \' to ''."""
        mysql = r"INSERT INTO test VALUES ('test\'value');"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # \' should be converted to ''
        assert "''" in result


class TestTypeConversions:
    """Test type conversion in DDL."""

    def test_int_to_integer(self):
        """INT converts to INTEGER."""
        mysql = "CREATE TABLE test (id INT);"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INTEGER" in result

    def test_tinyint_to_smallint(self):
        """TINYINT converts to SMALLINT."""
        mysql = "CREATE TABLE test (flag TINYINT);"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "SMALLINT" in result

    def test_removes_int_size(self):
        """Remove size specifier from INT."""
        mysql = "CREATE TABLE test (id INT(11));"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INT(11)" not in result
        assert "INTEGER" in result

    def test_enum_to_text(self):
        """ENUM converts to TEXT."""
        mysql = "CREATE TABLE test (status ENUM('active', 'inactive'));"
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "TEXT" in result
        assert "ENUM" not in result


class TestRealTDBExamples:
    """
    Tests using real examples from TrinityCore TDB database dumps.

    Source: TDB_full_world_442.25051_2025_05_11.sql
    """

    def test_access_requirement_table(self):
        """Convert real access_requirement table from TDB world dump."""
        # Extracted from TDB_full_world_442.25051_2025_05_11.sql
        mysql = """CREATE TABLE `access_requirement` (
  `mapId` int unsigned NOT NULL,
  `difficulty` tinyint unsigned NOT NULL DEFAULT '0',
  `level_min` tinyint unsigned NOT NULL DEFAULT '0',
  `level_max` tinyint unsigned NOT NULL DEFAULT '0',
  `item` int unsigned NOT NULL DEFAULT '0',
  `item2` int unsigned NOT NULL DEFAULT '0',
  `quest_done_A` int unsigned NOT NULL DEFAULT '0',
  `quest_done_H` int unsigned NOT NULL DEFAULT '0',
  `completed_achievement` int unsigned NOT NULL DEFAULT '0',
  `quest_failed_text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `comment` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`mapId`,`difficulty`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "CREATE TABLE" in result
        assert "ENGINE" not in result
        assert "CHARSET" not in result.upper()
        assert "COLLATE" not in result.upper()

    def test_access_requirement_insert_with_escaped_quote(self):
        """Convert INSERT with Zul'Farrak (real WoW dungeon name with apostrophe)."""
        # Real data from TDB dump - notice Zul'Farrak has apostrophe
        mysql = (
            "INSERT INTO `access_requirement` VALUES "
            "(209,1,0,0,0,0,0,0,0,NULL,'Zul\\'Farrak (Entrance)');"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO access_requirement VALUES" in result
        # The \' should be converted to ''
        assert "''" in result
        assert "Zul" in result

    def test_access_requirement_insert_multiple_escaped_quotes(self):
        """Convert INSERT with multiple locations containing apostrophes."""
        # Multiple entries with apostrophes: Zul'Farrak, Zul'Aman, Ahn'kahet, etc.
        mysql = """INSERT INTO `access_requirement` VALUES
(209,1,0,0,0,0,0,0,0,NULL,'Zul\\'Farrak (Entrance)'),
(568,1,0,0,0,0,0,0,0,NULL,'Zul\\'Aman (Entrance)'),
(619,1,0,0,0,0,0,0,0,NULL,'Ahn\\'kahet: The Old Kingdom (Heroic)');"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO access_requirement VALUES" in result
        # Each escaped quote should be converted
        assert result.count("''") >= 3

    def test_account_table_from_auth(self):
        """Convert account table from auth_database.sql."""
        # Extracted from sql/base/auth_database.sql
        mysql = (
            "CREATE TABLE `account` (\n"
            "  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifier',\n"
            "  `username` varchar(32) CHARACTER SET utf8mb4 "
            "COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',\n"
            "  `salt` binary(32) NOT NULL,\n"
            "  `verifier` binary(32) NOT NULL,\n"
            "  `session_key_auth` binary(40) DEFAULT NULL,\n"
            "  `email` varchar(255) CHARACTER SET utf8mb4 "
            "COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',\n"
            "  `joindate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n"
            "  `last_ip` varchar(64) CHARACTER SET utf8mb4 "
            "COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '127.0.0.1',\n"
            "  `failed_logins` int unsigned NOT NULL DEFAULT '0',\n"
            "  `locked` tinyint unsigned NOT NULL DEFAULT '0',\n"
            "  `expansion` tinyint unsigned NOT NULL DEFAULT '9',\n"
            "  PRIMARY KEY (`id`),\n"
            "  UNIQUE KEY `idx_username` (`username`)\n"
            ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 "
            "COLLATE=utf8mb4_unicode_ci COMMENT='Account System';"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # AUTO_INCREMENT should be converted
        assert "SERIAL" in result or "IDENTITY" in result or "id" in result
        assert "ENGINE" not in result
        assert "CHARACTER SET" not in result.upper()
        assert "COLLATE" not in result.upper()

    def test_complete_mysqldump_header(self):
        """Convert complete mysqldump header section."""
        # Real header from TDB dump
        mysql = """/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
CREATE TABLE `test` (`id` int NOT NULL);"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # All conditional comments should be removed
        assert "/*!" not in result
        assert "SET NAMES" not in result
        # Only the CREATE TABLE should remain
        assert "CREATE TABLE" in result

    def test_lock_unlock_tables(self):
        """Convert section with LOCK/UNLOCK TABLES (real pattern from TDB)."""
        mysql = """LOCK TABLES `access_requirement` WRITE;
/*!40000 ALTER TABLE `access_requirement` DISABLE KEYS */;
INSERT INTO `access_requirement` VALUES (33,1,0,0,0,0,0,0,0,NULL,'Shadowfang Keep');
/*!40000 ALTER TABLE `access_requirement` ENABLE KEYS */;
UNLOCK TABLES;"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "LOCK TABLES" not in result
        assert "UNLOCK TABLES" not in result
        assert "DISABLE KEYS" not in result
        assert "INSERT INTO" in result


class TestRealUpdateFileExamples:
    """
    Tests using real examples from update SQL files.

    Source: sql/old/4.4.x/world/24021_2024_06_02/2024_02_24_01_world.sql
    """

    def test_creature_text_with_escaped_quotes(self):
        """Convert creature_text INSERT with apostrophes in dialogue."""
        # Real example from 2024_02_24_01_world.sql line 112-114
        mysql = (
            "INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, "
            "`Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, "
            "`BroadcastTextId`, `TextRange`, `comment`) VALUES\n"
            "(162817, 0, 0, 'We take soul for ritual, you no stop!', "
            "12, 0, 100, 0, 0, 0, 0, 0, 'Torgok aggro'),\n"
            "(162817, 1, 0, 'Me never get... to see... ritual...', "
            "12, 0, 100, 0, 0, 0, 0, 0, 'Torgok death');"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO creature_text" in result

    def test_phase_name_with_apostrophe(self):
        """Convert phase_name INSERT with Won'sa (apostrophe in name)."""
        # Real example from 2024_02_24_01_world.sql line 355
        mysql = """INSERT INTO `phase_name` (`ID`,`Name`) VALUES
(15338,'Cosmetic - NPE - See Won\\'sa and Lana Jordan at Ogre Ruins pre quest at Ogre Ruins');"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO phase_name" in result
        # The escaped quote should be converted
        assert "''" in result
        assert "Won" in result

    def test_quest_request_items_with_apostrophe(self):
        """Convert quest text with I won't (contraction)."""
        # Real example from 2024_02_24_01_world.sql line 624-625
        mysql = (
            "INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, "
            "`EmoteOnIncomplete`, `EmoteOnCompleteDelay`, `EmoteOnIncompleteDelay`, "
            "`CompletionText`, `VerifiedBuild`) VALUES\n"
            "(55879, 0, 0, 0, 0, 'Please... help! I won\\'t last much longer!', 53262);"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO quest_request_items" in result
        # The escaped quote should be converted
        assert "''" in result

    def test_creature_text_with_let_contraction(self):
        """Convert creature_text with Let's (contraction)."""
        # Real example from 2024_02_24_01_world.sql line 486-490
        mysql = (
            "INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, "
            "`Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, "
            "`BroadcastTextId`, `TextRange`, `comment`) VALUES\n"
            "(156891,0,0,'All right, let\\'s see what we can find.', "
            "12, 0, 100, 0, 0, 153011, 178906, 0, 'Bjorn Stouthands to Player'),\n"
            "(167225,0,0,'Let\\'s see if we can find one of those rituals.', "
            "12, 0, 100, 0, 0, 155935, 196409, 0, 'Lana Jordan to Player');"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO creature_text" in result
        assert "''" in result

    def test_creature_loot_with_torgok_possessive(self):
        """Convert loot template with Torgok's (possessive apostrophe)."""
        # Real example from 2024_02_24_01_world.sql line 275-276
        mysql = (
            "INSERT INTO `creature_loot_template` (`Entry`,`Item`,`Reference`,"
            "`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,"
            "`Comment`) VALUES\n"
            "(162817,176398,0,100,0,1,0,1,1,'Torgok - Torgok\\'s Reagent Pouch');"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "INSERT INTO creature_loot_template" in result
        assert "''" in result

    def test_update_with_string_id(self):
        """Convert UPDATE with StringId containing underscore-separated words."""
        # Real example from 2024_02_24_01_world.sql line 75-76
        mysql = """UPDATE `creature` SET `StringId`= "captain_garrick_plains" WHERE `guid`=8000018;
UPDATE `creature` SET `StringId` = 'henry_garrick_ogre_ruins_prisoner' WHERE `guid`=8000023;"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "UPDATE creature SET" in result

    def test_mixed_ddl_dml_from_update_file(self):
        """Convert mixed UPDATE and DELETE statements."""
        # Real pattern from update files
        mysql = """DELETE FROM `creature` WHERE `guid` BETWEEN 8000041 AND 8000058;
UPDATE `creature_template` SET `faction`=1 WHERE `entry`=174955;
UPDATE `creature_template` SET `npcflag`=2 WHERE `entry` IN (154300,156891);"""
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        assert "DELETE FROM creature" in result
        assert "UPDATE creature_template" in result


class TestComplexScenarios:
    """Test complex conversion scenarios."""

    def test_insert_with_special_characters(self):
        """Convert INSERT with special WoW NPC names."""
        mysql = (
            "INSERT INTO creature_template VALUES "
            "(10082, 'Zul\\'Farrak Dead Hero', NULL, NULL, 0, 45, 45, 16);"
        )
        pipeline = create_default_pipeline()
        result = pipeline.convert(mysql)

        # Quote should be properly escaped
        assert "INSERT INTO creature_template VALUES" in result
        # The escaped quote should be converted
        assert "''" in result or "Zul" in result
